"""ADR-072 ``--global`` refusal, asserted at the FILESYSTEM, not at a mock.

``tests/hermes_cli/test_apply_model_switch_result_context.py::
test_global_switch_refuses_to_persist_under_adr072`` asserts the refusal by
monkeypatching ``cli.save_config_value`` and requiring ``writes == []``.  That
is a statement about ONE module-level name.  It is green against a production
implementation that clobbers ``config.yaml`` by any other route — a
function-local import, ``utils.atomic_roundtrip_yaml_update`` called directly, a
raw ``yaml.dump``.  Measured, not theorised: inserting

    from utils import atomic_roundtrip_yaml_update
    from hermes_constants import get_hermes_home
    atomic_roundtrip_yaml_update(get_hermes_home() / "config.yaml",
                                 "model.context_length", None)

into the ``if persist_global:`` branch leaves all three of that test's
assertions passing while ``config.yaml`` is rewritten on disk.

ADR-072's property is "a manual ``/model --global`` cannot clobber the
roster-generated ``config.yaml``".  The observable that carries that property is
the file, so this test asserts the file — byte-for-byte, with a pre-existing
roster-shaped config in place, which is the state a live profile is actually in.
"""

from __future__ import annotations

from unittest.mock import patch

from hermes_constants import get_hermes_home
from hermes_cli.model_switch import ModelSwitchResult


ROSTER_CONFIG = """\
# Generated by scripts/generate_profile_provider.py — do not hand-edit.
model:
  default: roster/model
  provider: roster-provider
  context_length: 272000
"""


class _StubCLI:
    """Minimum attrs ``_apply_model_switch_result`` reads on ``self``."""

    agent = None
    model = ""
    provider = ""
    requested_provider = ""
    api_key = ""
    _explicit_api_key = ""
    base_url = ""
    _explicit_base_url = ""
    api_mode = ""
    _pending_model_switch_note = ""


def _result():
    return ModelSwitchResult(
        success=True,
        new_model="shared-model",
        target_provider="custom",
        api_key="k",
        base_url="https://custom.example/v1",
        api_mode=None,
        provider_label="custom",
        model_info=None,
        warning_message=None,
    )


def _apply(monkeypatch, persist_global):
    import cli as cli_mod

    printed: list[str] = []
    monkeypatch.setattr(
        cli_mod, "_cprint", lambda *a, **_k: printed.append(str(a[0]) if a else "")
    )
    cli = _StubCLI()
    # NOTE: save_config_value is deliberately NOT patched. Patching it is
    # exactly the hole this file exists to close — the real function must be
    # allowed to run so that a call to it shows up as a changed file.
    with patch(
        "hermes_cli.model_switch.resolve_display_context_length", return_value=0
    ):
        cli_mod.HermesCLI._apply_model_switch_result(cli, _result(), persist_global)
    return cli, printed


def test_global_switch_leaves_an_existing_config_yaml_byte_identical(monkeypatch):
    cfg = get_hermes_home() / "config.yaml"
    cfg.parent.mkdir(parents=True, exist_ok=True)
    cfg.write_text(ROSTER_CONFIG, encoding="utf-8")
    before = cfg.read_bytes()

    cli, printed = _apply(monkeypatch, persist_global=True)

    after = cfg.read_bytes()
    assert after == before, (
        "ADR-072 violated: `/model --global` rewrote the roster-generated "
        "config.yaml.\n--- before ---\n"
        f"{before.decode('utf-8', 'replace')}\n--- after ---\n"
        f"{after.decode('utf-8', 'replace')}"
    )
    # The refusal must still be explained, and the session swap must still land
    # — a no-op that also declined to switch would satisfy the file assertion.
    assert any("ADR-072" in line for line in printed), printed
    assert cli.model == "shared-model" and cli.provider == "custom"


def test_global_switch_does_not_create_a_config_yaml_when_none_exists(monkeypatch):
    """The missing-config case, which the byte-identity test cannot reach.

    A fresh profile has no ``config.yaml``.  ``save_config_value`` CREATES one
    (``config_path.parent.mkdir(...)`` then ``atomic_roundtrip_yaml_update``),
    so a reintroduced persist is visible here as a file appearing from nothing.
    """
    cfg = get_hermes_home() / "config.yaml"
    if cfg.exists():
        cfg.unlink()

    cli, printed = _apply(monkeypatch, persist_global=True)

    assert not cfg.exists(), (
        "ADR-072 violated: `/model --global` created a config.yaml on a profile "
        "that had none. Contents:\n" + cfg.read_text(encoding="utf-8")
    )
    assert any("ADR-072" in line for line in printed), printed
    assert cli.model == "shared-model"


def test_session_only_switch_is_not_silently_given_the_adr072_refusal(monkeypatch):
    """Guards the other half of the branch.

    An implementation that refused (and printed the ADR-072 notice) for BOTH
    ``persist_global`` values would satisfy every assertion in the committed
    ADR-072 test.  The session-only path is supposed to say "session only — add
    --global to persist", i.e. it must not claim manifest governance.
    """
    cli, printed = _apply(monkeypatch, persist_global=False)

    assert any("session only" in line for line in printed), printed
    assert not any("ADR-072" in line for line in printed), (
        "the session-only path printed the --global manifest-governance "
        f"refusal: {printed!r}"
    )
    assert cli.model == "shared-model"
